version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tienda
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 tienda.wsgi:application
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - mynetwork
    environment:
      - POSTGRES_DB=tienda
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=developer
      - DATABASE_HOST=db  # Añadir esto
      - DATABASE_PORT=5432  # Añadir esto
      - DEBUG=True

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
