# Generated by Django 5.0.4 on 2024-05-17 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=200, null=True)),
                ('direccion', models.CharField(max_length=200, null=True)),
                ('provincia', models.CharField(max_length=200, null=True)),
                ('codigo_postal', models.CharField(max_length=200, null=True)),
                ('es_entrega', models.BooleanField(default=True)),
                ('user_id', models.OneToOneField(db_column='', on_delete=django.db.models.deletion.RESTRICT, related_name='get_Direccion_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'direccion',
                'verbose_name_plural': 'direcciones',
                'db_table': 't_direccion',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=9)),
                ('tel', models.CharField(blank=True, max_length=12, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagen_profile/')),
                ('count', models.PositiveIntegerField(default=0)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('bloqueado', models.BooleanField(default=False)),
                ('user_id', models.OneToOneField(db_column='', on_delete=django.db.models.deletion.RESTRICT, related_name='get_Profile_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 't_perfil',
            },
        ),
    ]
