# Generated by Django 5.0.4 on 2024-05-29 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_direccion_options_alter_categoria_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='carrito_detalle',
            constraint=models.UniqueConstraint(fields=('user_id', 'producto_id'), name='unique_user_producto_id'),
        ),
    ]
