# Generated by Django 5.0.4 on 2024-06-04 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_producto_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_con_iva',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
