# Generated by Django 5.0.4 on 2024-06-07 21:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_imagenproducto_imagen_principal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.UniqueConstraint(fields=('user_id',), name='unique_user_id'),
        ),
    ]
