# Generated by Django 5.0.4 on 2024-06-09 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_carrito_detalle_session_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='count',
            new_name='contador',
        ),
    ]
