# Generated by Django 5.0.4 on 2024-06-13 15:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_producto_en_oferta_producto_precio_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_detalle',
            name='pedido_cabecera_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='main.pedido_cabecera'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
