# Generated by Django 5.0.4 on 2024-06-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_pedido_detalle_pedido_cabecera_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_con_iva',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_oferta',
        ),
        migrations.AddField(
            model_name='pedido_cabecera',
            name='order_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido_detalle',
            name='porcentaje',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Carrito_Detalle',
        ),
    ]
